### ISSUE TITLE
Add configurable skip button to steps

### ISSUE THREAD

**Issue by afaikafk** [Outernet-Project/librarian-setup#1]
Steps should specify whether user can skip them or not, and if they are skippable, UI should provide appropriate controls to do so.

**Comment by foxbunny** [comment]
We no longer need this. Steps can define their own skip mechanism. See [this](https://github.com/Outernet-Project/librarian-ondd/blob/4476c52a9ed58f66c682700a298023fff7d896b7/librarian_ondd/setup.py#L37-L62) for an example.
