### ISSUE TITLE
Back button does not work

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian-setup#5]
Looks like the work of YABT. :) The button points to `/en/setup/?step_param=1` instead of `/en/setup/?step=1`. Typing in the step number in address bar works fine.

**Comment by afaikafk** [comment]
I think this works in the current version

**Comment by ben-en** [comment]
Confirmed functional at this time.

**Comment by foxbunny** [comment]
Functional _at this time_. :)))
